server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: pizza-order-ms
  data:
    mongodb:
      uri: mongodb://Michael_Amdocs:amdocs123@ds135427.mlab.com:35427/michael_pizza?retryWrites=false
