server:
  port: 8080

cros:
  origins: http://localhost:3000

spring:
  application:
    name: pizza-location-ms
  data:
    mongodb:
      uri: mongodb://Michael_Amdocs:amdocs123@ds135427.mlab.com:35427/michael_pizza?retryWrites=false
      collection-name: pizza_location

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
