version: '3.8'

services:
  mongodb_pizza:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      #- mongodb_pizza:/data/db
      - ./Services/mongo-init/:/docker-entrypoint-initdb.d/:ro
    command: --quiet
#  mongo-seed:
#    build: ./Services/mongo-seed
#    depends_on:
#      - mongodb_pizza
  pizza-location:
    build: ./Backend/pizza-location-ms
    restart: always
    ports:
      - 8080:8085
    depends_on:
      - mongodb_pizza

volumes:
  mongodb_pizza:
