version: '3.8'

services:
  mongodb_pizza:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      #- mongodb_pizza:/data/db
      - ./Services/mongo-init/:/docker-entrypoint-initdb.d/:ro
    command: --quiet
#  mongo-seed:
#    build: ./Services/mongo-seed
#    depends_on:
#      - mongodb_pizza
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  pizza-location:
    build: ./Backend/pizza-location-ms
    restart: always
    ports:
      - 8085:8085
    depends_on:
      - mongodb_pizza
  pizza-menu:
    build: ./Backend/pizza-menu-ms
    restart: always
    ports:
      - 8086:8086
    depends_on:
      - mongodb_pizza

volumes:
  mongodb_pizza:
