server:
  port: 8081

cros:
  origins: http://localhost:3000

logging:
  level:
    com:
      example: DEBUG

spring:
  application:
    name: pizza-menu-ms
  data:
    mongodb:
      uri: mongodb://Michael:michael123@ds135427.mlab.com:35427/michael_pizza?retryWrites=false
      pizzas-collection-name: pizza_menu_pizzas
      toppings-collection-name: pizza_menu_toppings
      drinks-collection-name: pizza_menu_drinks

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

