---
server:
  port: 8086

cross:
  origins: http://localhost:3000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/local?retryWrites=false

logging:
  level:
    com:
      example: DEBUG
