const actionType = {
    INITIALIZE_STATE: 'INITIALIZE_STATE',
    GET_MENU_LIST: 'GET_MENU_LIST',
    GET_CITY_LIST: 'GET_CITY_LIST',
    GET_ORDER_LIST: 'GET_ORDER_LIST',
    GET_ORDER: 'GET_ORDER',
    CREATE_ORDER: 'CREATE_ORDER',
    ADD_PIZZA_TO_CART: 'ADD_PIZZA_TO_CART',
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    UPDATE_CURRENT_PIZZA_NUMBER_TO_CART: 'UPDATE_CURRENT_PIZZA_NUMBER_TO_CART',
    ADD_NUMBER_OF_PIZZAS_TO_CART: 'ADD_NUMBER_OF_PIZZAS_TO_CART',
    ADD_TOPPINGS_TO_CART: 'ADD_TOPPINGS_TO_CART',
    ADD_DRINKS_TO_CART: 'ADD_DRINKS_TO_CART',
    UPDATE_ORDER_PRICE: 'UPDATE_ORDER_PRICE',
    UPDATE_TOTAL_PRICE: 'UPDATE_TOTAL_PRICE',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    REARRANGE_CART_ORDERS: 'REARRANGE_CART_ORDERS'
};

export default actionType;