---
server:
  port: 8085

cross:
  origins: http://localhost:3000

spring:
  data:
    mongodb:
      uri: mongodb://mongodb_pizza:27017/local?retryWrites=false

logging:
  level:
    com:
      example: DEBUG